version: "3.7"

services:
    ws2801rpi:
        image: "djhofmann/ws2801:latest"
        restart: "always"
        privileged: true
        ports:
            - 3000:2684
        volumes:
            - /sys/:/sys/
            - /lib/modules/:/lib/modules
        devices:
            - /dev/spidev0.0:/dev/spidev0.0

